### ISSUE TITLE
Make status checks take consecutive failures in time into account to get rid of temporary failures

### ISSUE THREAD

**Issue by nebril** [Mirantis/k8s-AppController#106]
When there is a temporary network failure, we should have the ability to wait for several consecutive checks to ensure that the failure is legit.

Each deployment graph vertex should have possibility to specify this behaviour.

Implementation suggestion - put this information in resource definition k8s annotations.
Proposal of specification of this behaviour:
```
"failLegitimacy": {
   "failsInTime": { # this will cause the status of vertex to be failed if it fails 3 times in 10 second time interval
      "failCount": 3,
     "time": 10,
   }
}
```

**Comment by pigmej** [comment]
We should also take them into account "just after triggering previous event", so there should be some grace period.

**Comment by jellonek** [comment]
IMO this should be in sync with forgiveness topic ( https://github.com/kubernetes/kubernetes/issues/1574 ).

**Comment by pigmej** [comment]
@jellonek as a second phase for sure ;) For now we need internal mechanism to handle described situation ;-) Then we will need to extend it to more cases (forgiveness, node maintenance etc) and add more control (temporary disable etc etc).

**Comment by jellonek** [comment]
Right, step after step.

**Comment by pigmej** [comment]
Solved by https://github.com/Mirantis/k8s-AppController/pull/174
