### ISSUE TITLE
Support for better state checking of Service stuff

### ISSUE THREAD

**Issue by pigmej** [Mirantis/k8s-AppController#17]
There may be a need that for Service dependency we will need to check the health of objects that is selected by Service (service selector). Which will basically mean that we will replace internally dependency on Service by dependency on all objects that are selected by Service.

It will be much easier for user to depend on `mysql` service than on galera/mariadb components itself.

**Comment by nebril** [comment]
Should we make this implicit? I think I would rather make user define his graph in a way that explicitly shows the service underlying objects as parents.

**Comment by pigmej** [comment]
we can't and shouldn't make it implicit.

When you deploy some app that for example depends on mysql, you shouldn't need changing graph when you change single mysql to galera cluster. The same for already existing stuff.

We may make this optional, or non default behaviour obviously.

**Comment by nebril** [comment]
@pigmej you need to change the graph to adjust it from single mysql to galera anyway. So I am still opting for setting the dependencies by user explicitly on underlying pods, in which case the need for checking state of Service is.

Another reason to do it this way is that  is no notion of Service state in Kubernetes core (AFAIK).

**Comment by nebril** [comment]
On the other hand, it might come in handy!
