### ISSUE TITLE
Write more elaborate e2e tests.

### ISSUE THREAD

**Issue by nebril** [Mirantis/k8s-AppController#189]
We currently have working CI for e2e tests with two simple scenarios. We should either write additional tests or rewrite the test suite to make it possible to define tests in non-code files.

**Comment by dshulyak** [comment]
I will implement interface that will allow to consume our examples as e2e tests. I dont really like lots of sleep in examples, so I might not use them as is

**Comment by pigmej** [comment]
Yeah our sleeps there are bad... would be cool to remove them even.

**Comment by dshulyak** [comment]
I will close this one
