### ISSUE TITLE
ThirdPartyResource clients (definitions and dependencies) should not use default namespace when cluster allows it.

### ISSUE THREAD

**Issue by nebril** [Mirantis/k8s-AppController#192]
Historically, all TPR objects were created in and retrieved from default namespace due to a bug in ThirdPartyResources implementation that prevented the resources from being stored in a non-default namespace.

As of k8s version 1.5.2 (maybe earlier) you can create TPRs in non-default namespace. We should change the client code to use namespace AC pod lives in. Changes should be done in 
https://github.com/Mirantis/k8s-AppController/blob/master/pkg/client/dependencies.go
and
https://github.com/Mirantis/k8s-AppController/blob/master/pkg/client/resdef.go
files.

You need to check which k8s version introduced the TPR fix.

Cluster version should be checked and default namespace should be chosen for clusters that do not support storing  TPR objects in non-default namespaces.

**Comment by pigmej** [comment]
Will be closed by https://github.com/Mirantis/k8s-AppController/pull/200
