### ISSUE TITLE
Allow per-dependency metadata

### ISSUE THREAD

**Issue by gluke77** [Mirantis/k8s-AppController#63]
Currently only resources are stored in dependency graph so we can only add metadata to them. We need to be able to add metadata to dependencies. This needs dependency graph to be refactored.

This issue also relates to #37

**Comment by nebril** [comment]
Wasn't dependency metadata added in ReplicaSet support?

**Comment by gluke77** [comment]
@nebril Nope, we added meta to RC Resource, not to dependency, as a temporary solution.

**Comment by jellonek** [comment]
Are you sure?

https://github.com/Mirantis/k8s-AppController/commit/1646fe5ac08055702c85c6b94472684617a08361#diff-6506411c06d0efa42d686cce616f20e9R35

**Comment by jellonek** [comment]
Ok. It's then replicated into RC Resource because of current shape of scheduler.
So this issue is probably more about scheduler refactor to operate on dependencies pointing to reources instead of operating on resources.

**Comment by gluke77** [comment]
In fact I got another idea -- we'll leave depgraph as a set of resources and will introduce dependencies as a storage for meta, i.e. these new entities would be optional. Have to validate the idea thou.

**Comment by jellonek** [comment]
The key is that depgraph is now map of ScheduledResources, which are common to different dependencies.
IMO this should be separated, depgraph should be based on dependencies which will contain scheduled resources, but with additional metadata, which then could be used by Status check per dependency and not per resource as it is right now.
With this change we could depend on Resource with different meta based status for different deps.
Still this would require passing this meta into status check which should be removed from Create methods.

**Comment by gluke77** [comment]
@jellonek Well, with depgraph based only on dependencies we could get issues with creating resources. E.g. we won't be able to define if several dependencies depend on the same resource.

**Comment by jellonek** [comment]
We could, if we would store resources in additional separate map, from which we would get already created resources.

**Comment by gluke77** [comment]
@jellonek so we separately store resources and deps. How does it differ from what I suggested? ,)

**Comment by jellonek** [comment]
I wanted to make graph from deps pointing to resources, not as a set of resources.

**Comment by gluke77** [comment]
Done by #74
